services:
  meeting-bot:
    image: tonymc016/meeting-bot-aheadx:0.1.62
    pull_policy: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHROME_PATH=/usr/bin/google-chrome
    ports:
      - "3010:3000"
    shm_size: '1gb'
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
